In [1]:
pip list

Package                           Version
--------------------------------- ------------------
aext-assistant                    4.0.15
aext-assistant-server             4.0.15
aext-core                         4.0.15
aext-core-server                  4.0.15
aext-panels                       4.0.15
aext-panels-server                4.0.15
aext-share-notebook               4.0.15
aext-share-notebook-server        4.0.15
aext-shared                       4.0.15
aiobotocore                       2.12.3
aiohappyeyeballs                  2.4.0
aiohttp                           3.10.5
aioitertools                      0.7.1
aiosignal                         1.2.0
alabaster                         0.7.16
altair                            5.0.1
anaconda-anon-usage               0.4.4
anaconda-catalogs                 0.2.0
anaconda-client                   1.12.3
anaconda-cloud-auth               0.5.1
anaconda-navigator                2.6.3
anaconda-project                  0.11.1
annotated-types                   0.6.0
anyio                             4.2.0
appdirs                           1.4.4
archspec                          0.2.3
argon2-cffi                       21.3.0
argon2-cffi-bindings              21.2.0
arrow                             1.2.3
astroid                           2.14.2
astropy                           6.1.3
astropy-iers-data                 0.2024.9.2.0.33.23
asttokens                         2.0.5
async-lru                         2.0.4
atomicwrites                      1.4.0
attrs                             23.1.0
Automat                           20.2.0
autopep8                          2.0.4
Babel                             2.11.0
bcrypt                            3.2.0
beautifulsoup4                    4.12.3
binaryornot                       0.4.4
black                             24.8.0
bleach                            4.1.0
blinker                           1.6.2
bokeh                             3.6.0
boltons                           23.0.0
botocore                          1.34.69
Bottleneck                        1.3.7
Brotli                            1.0.9
cachetools                        5.3.3
certifi                           2024.8.30
cffi                              1.17.1
chardet                           4.0.0
charset-normalizer                3.3.2
click                             8.1.7
cloudpickle                       3.0.0
colorama                          0.4.6
colorcet                          3.1.0
comm                              0.2.1
conda                             24.11.0
conda-build                       24.9.0
conda-content-trust               0.2.0
conda_index                       0.5.0
conda-libmamba-solver             24.9.0
conda-pack                        0.7.1
conda-package-handling            2.3.0
conda_package_streaming           0.10.0
conda-repo-cli                    1.0.114
conda-token                       0.5.0+1.g2209e04
constantly                        23.10.4
contourpy                         1.2.0
cookiecutter                      2.6.0
cryptography                      43.0.0
cssselect                         1.2.0
cycler                            0.11.0
cytoolz                           0.12.2
dask                              2024.8.2
dask-expr                         1.1.13
datashader                        0.16.3
debugpy                           1.6.7
decorator                         5.1.1
defusedxml                        0.7.1
diff-match-patch                  20200713
dill                              0.3.8
distributed                       2024.8.2
distro                            1.9.0
docstring-to-markdown             0.11
docutils                          0.18.1
et-xmlfile                        1.1.0
executing                         0.8.3
fastjsonschema                    2.16.2
filelock                          3.13.1
flake8                            7.0.0
Flask                             3.0.3
fonttools                         4.51.0
frozendict                        2.4.2
frozenlist                        1.4.0
fsspec                            2024.6.1
gensim                            4.3.3
gitdb                             4.0.7
GitPython                         3.1.43
greenlet                          3.0.1
h11                               0.14.0
h5py                              3.11.0
HeapDict                          1.0.1
holoviews                         1.19.1
httpcore                          1.0.2
httpx                             0.27.0
hvplot                            0.11.0
hyperlink                         21.0.0
idna                              3.7
imagecodecs                       2023.1.23
imageio                           2.33.1
imagesize                         1.4.1
imbalanced-learn                  0.12.3
importlib-metadata                7.0.1
incremental                       22.10.0
inflection                        0.5.1
iniconfig                         1.1.1
intake                            2.0.7
intervaltree                      3.1.0
ipykernel                         6.28.0
ipython                           8.27.0
ipython-genutils                  0.2.0
ipywidgets                        7.8.1
isort                             5.13.2
itemadapter                       0.3.0
itemloaders                       1.1.0
itsdangerous                      2.2.0
jaraco.classes                    3.2.1
jedi                              0.19.1
jellyfish                         1.0.1
Jinja2                            3.1.4
jmespath                          1.0.1
joblib                            1.4.2
json5                             0.9.6
jsonpatch                         1.33
jsonpointer                       2.1
jsonschema                        4.23.0
jsonschema-specifications         2023.7.1
jupyter                           1.0.0
jupyter_client                    8.6.0
jupyter-console                   6.6.3
jupyter_core                      5.7.2
jupyter-events                    0.10.0
jupyter-lsp                       2.2.0
jupyter_server                    2.14.1
jupyter_server_terminals          0.4.4
jupyterlab                        4.2.5
jupyterlab-pygments               0.1.2
jupyterlab_server                 2.27.3
jupyterlab-widgets                1.0.0
keyring                           24.3.1
kiwisolver                        1.4.4
lazy_loader                       0.4
lazy-object-proxy                 1.10.0
lckr_jupyterlab_variableinspector 3.1.0
libarchive-c                      5.1
libmambapy                        1.5.8
linkify-it-py                     2.0.0
llvmlite                          0.43.0
lmdb                              1.4.1
locket                            1.0.0
lxml                              5.2.1
lz4                               4.3.2
Markdown                          3.4.1
markdown-it-py                    2.2.0
MarkupSafe                        2.1.3
matplotlib                        3.9.2
matplotlib-inline                 0.1.6
mccabe                            0.7.0
mdit-py-plugins                   0.3.0
mdurl                             0.1.0
menuinst                          2.1.2
mistune                           2.0.4
mkl_fft                           1.3.10
mkl_random                        1.2.7
mkl-service                       2.4.0
more-itertools                    10.3.0
mpmath                            1.3.0
msgpack                           1.0.3
multidict                         6.0.4
multipledispatch                  0.6.0
mypy                              1.11.2
mypy-extensions                   1.0.0
navigator-updater                 0.5.1
nbclient                          0.8.0
nbconvert                         7.16.4
nbformat                          5.10.4
nest-asyncio                      1.6.0
networkx                          3.3
nltk                              3.9.1
notebook                          7.2.2
notebook_shim                     0.2.3
numba                             0.60.0
numexpr                           2.8.7
numpy                             1.26.4
numpydoc                          1.7.0
openpyxl                          3.1.5
overrides                         7.4.0
packaging                         24.1
pandas                            2.2.2
pandocfilters                     1.5.0
panel                             1.5.2
param                             2.1.1
paramiko                          2.8.1
parsel                            1.8.1
parso                             0.8.3
partd                             1.4.1
pathspec                          0.10.3
patsy                             0.5.6
pexpect                           4.8.0
pickleshare                       0.7.5
pillow                            10.4.0
pip                               24.2
pkce                              1.0.3
pkginfo                           1.10.0
platformdirs                      3.10.0
plotly                            5.24.1
pluggy                            1.0.0
ply                               3.11
prometheus-client                 0.14.1
prompt-toolkit                    3.0.43
Protego                           0.1.16
protobuf                          4.25.3
psutil                            5.9.0
ptyprocess                        0.7.0
pure-eval                         0.2.2
py-cpuinfo                        9.0.0
pyarrow                           16.1.0
pyasn1                            0.4.8
pyasn1-modules                    0.2.8
pycodestyle                       2.11.1
pycosat                           0.6.6
pycparser                         2.21
pyct                              0.5.0
pycurl                            7.45.3
pydantic                          2.8.2
pydantic_core                     2.20.1
pydeck                            0.8.0
PyDispatcher                      2.0.5
pydocstyle                        6.3.0
pyerfa                            2.0.1.4
pyflakes                          3.2.0
Pygments                          2.15.1
PyJWT                             2.8.0
pylint                            2.16.2
pylint-venv                       3.0.3
pyls-spyder                       0.4.0
PyNaCl                            1.5.0
pyodbc                            5.1.0
pyOpenSSL                         24.2.1
pyparsing                         3.1.2
PyQt5                             5.15.10
PyQt5-sip                         12.13.0
PyQtWebEngine                     5.15.6
PySocks                           1.7.1
pytest                            7.4.4
python-dateutil                   2.9.0.post0
python-dotenv                     0.21.0
python-json-logger                2.0.7
python-lsp-black                  2.0.0
python-lsp-jsonrpc                1.1.2
python-lsp-server                 1.10.0
python-slugify                    5.0.2
pytoolconfig                      1.2.6
pytz                              2024.1
pyviz_comms                       3.0.2
PyWavelets                        1.7.0
pywin32                           305.1
pywin32-ctypes                    0.2.2
pywinpty                          2.0.10
PyYAML                            6.0.1
pyzmq                             25.1.2
QDarkStyle                        3.2.3
qstylizer                         0.2.2
QtAwesome                         1.3.1
qtconsole                         5.5.1
QtPy                              2.4.1
queuelib                          1.6.2
referencing                       0.30.2
regex                             2024.9.11
requests                          2.32.3
requests-file                     1.5.1
requests-toolbelt                 1.0.0
rfc3339-validator                 0.1.4
rfc3986-validator                 0.1.1
rich                              13.7.1
rope                              1.12.0
rpds-py                           0.10.6
Rtree                             1.0.1
ruamel.yaml                       0.18.6
ruamel.yaml.clib                  0.2.8
ruamel-yaml-conda                 0.17.21
s3fs                              2024.6.1
scikit-image                      0.24.0
scikit-learn                      1.5.1
scipy                             1.13.1
Scrapy                            2.11.1
seaborn                           0.13.2
semver                            3.0.2
Send2Trash                        1.8.2
service-identity                  18.1.0
setuptools                        75.1.0
sip                               6.7.12
six                               1.16.0
smart-open                        5.2.1
smmap                             4.0.0
sniffio                           1.3.0
snowballstemmer                   2.2.0
sortedcontainers                  2.4.0
soupsieve                         2.5
Sphinx                            7.3.7
sphinxcontrib-applehelp           1.0.2
sphinxcontrib-devhelp             1.0.2
sphinxcontrib-htmlhelp            2.0.0
sphinxcontrib-jsmath              1.0.1
sphinxcontrib-qthelp              1.0.3
sphinxcontrib-serializinghtml     1.1.10
spyder                            5.5.1
spyder-kernels                    2.5.0
SQLAlchemy                        2.0.34
stack-data                        0.2.0
statsmodels                       0.14.2
streamlit                         1.37.1
sympy                             1.13.2
tables                            3.10.1
tabulate                          0.9.0
tblib                             1.7.0
tenacity                          8.2.3
terminado                         0.17.1
text-unidecode                    1.3
textdistance                      4.2.1
threadpoolctl                     3.5.0
three-merge                       0.1.1
tifffile                          2023.4.12
tinycss2                          1.2.1
tldextract                        5.1.2
toml                              0.10.2
tomli                             2.0.1
tomlkit                           0.11.1
toolz                             0.12.0
tornado                           6.4.1
tqdm                              4.66.5
traitlets                         5.14.3
truststore                        0.8.0
Twisted                           23.10.0
twisted-iocpsupport               1.0.2
typing_extensions                 4.11.0
tzdata                            2023.3
uc-micro-py                       1.0.1
ujson                             5.10.0
unicodedata2                      15.1.0
Unidecode                         1.3.8
urllib3                           2.2.3
w3lib                             2.1.2
watchdog                          4.0.1
wcwidth                           0.2.5
webencodings                      0.5.1
websocket-client                  1.8.0
Werkzeug                          3.0.3
whatthepatch                      1.0.2
wheel                             0.44.0
widgetsnbextension                3.6.6
win-inet-pton                     1.1.0
wrapt                             1.14.1
xarray                            2023.6.0
xlwings                           0.32.1
xyzservices                       2022.9.0
yapf                              0.40.2
yarl                              1.11.0
zict                              3.0.0
zipp                              3.17.0
zope.interface                    5.4.0
zstandard                         0.23.0
Note: you may need to restart the kernel to use updated packages.

In [3]:
pip install ydata_profiling

Collecting ydata_profiling
  Downloading ydata_profiling-4.16.1-py2.py3-none-any.whl.metadata (22 kB)
Requirement already satisfied: scipy<1.16,>=1.4.1 in c:\users\yesmi\anaconda3\lib\site-packages (from ydata_profiling) (1.13.1)
Requirement already satisfied: pandas!=1.4.0,<3.0,>1.1 in c:\users\yesmi\anaconda3\lib\site-packages (from ydata_profiling) (2.2.2)
Requirement already satisfied: matplotlib<=3.10,>=3.5 in c:\users\yesmi\anaconda3\lib\site-packages (from ydata_profiling) (3.9.2)
Requirement already satisfied: pydantic>=2 in c:\users\yesmi\anaconda3\lib\site-packages (from ydata_profiling) (2.8.2)
Requirement already satisfied: PyYAML<6.1,>=5.0.0 in c:\users\yesmi\anaconda3\lib\site-packages (from ydata_profiling) (6.0.1)
Requirement already satisfied: jinja2<3.2,>=2.11.1 in c:\users\yesmi\anaconda3\lib\site-packages (from ydata_profiling) (3.1.4)
Collecting visions<0.8.2,>=0.7.5 (from visions[type_image_path]<0.8.2,>=0.7.5->ydata_profiling)
  Downloading visions-0.8.1-py3-none-any.whl.metadata (11 kB)
Requirement already satisfied: numpy<2.2,>=1.16.0 in c:\users\yesmi\anaconda3\lib\site-packages (from ydata_profiling) (1.26.4)
Collecting htmlmin==0.1.12 (from ydata_profiling)
  Downloading htmlmin-0.1.12.tar.gz (19 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Collecting phik<0.13,>=0.11.1 (from ydata_profiling)
  Downloading phik-0.12.4-cp312-cp312-win_amd64.whl.metadata (5.6 kB)
Requirement already satisfied: requests<3,>=2.24.0 in c:\users\yesmi\anaconda3\lib\site-packages (from ydata_profiling) (2.32.3)
Requirement already satisfied: tqdm<5,>=4.48.2 in c:\users\yesmi\anaconda3\lib\site-packages (from ydata_profiling) (4.66.5)
Requirement already satisfied: seaborn<0.14,>=0.10.1 in c:\users\yesmi\anaconda3\lib\site-packages (from ydata_profiling) (0.13.2)
Collecting multimethod<2,>=1.4 (from ydata_profiling)
  Downloading multimethod-1.12-py3-none-any.whl.metadata (9.6 kB)
Requirement already satisfied: statsmodels<1,>=0.13.2 in c:\users\yesmi\anaconda3\lib\site-packages (from ydata_profiling) (0.14.2)
Collecting typeguard<5,>=3 (from ydata_profiling)
  Downloading typeguard-4.4.2-py3-none-any.whl.metadata (3.8 kB)
Collecting imagehash==4.3.1 (from ydata_profiling)
  Downloading ImageHash-4.3.1-py2.py3-none-any.whl.metadata (8.0 kB)
Collecting wordcloud>=1.9.3 (from ydata_profiling)
  Downloading wordcloud-1.9.4-cp312-cp312-win_amd64.whl.metadata (3.5 kB)
Collecting dacite>=1.8 (from ydata_profiling)
  Downloading dacite-1.9.2-py3-none-any.whl.metadata (17 kB)
Requirement already satisfied: numba<=0.61,>=0.56.0 in c:\users\yesmi\anaconda3\lib\site-packages (from ydata_profiling) (0.60.0)
Requirement already satisfied: PyWavelets in c:\users\yesmi\anaconda3\lib\site-packages (from imagehash==4.3.1->ydata_profiling) (1.7.0)
Requirement already satisfied: pillow in c:\users\yesmi\anaconda3\lib\site-packages (from imagehash==4.3.1->ydata_profiling) (10.4.0)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\yesmi\anaconda3\lib\site-packages (from jinja2<3.2,>=2.11.1->ydata_profiling) (2.1.3)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\yesmi\anaconda3\lib\site-packages (from matplotlib<=3.10,>=3.5->ydata_profiling) (1.2.0)
Requirement already satisfied: cycler>=0.10 in c:\users\yesmi\anaconda3\lib\site-packages (from matplotlib<=3.10,>=3.5->ydata_profiling) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\yesmi\anaconda3\lib\site-packages (from matplotlib<=3.10,>=3.5->ydata_profiling) (4.51.0)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\yesmi\anaconda3\lib\site-packages (from matplotlib<=3.10,>=3.5->ydata_profiling) (1.4.4)
Requirement already satisfied: packaging>=20.0 in c:\users\yesmi\anaconda3\lib\site-packages (from matplotlib<=3.10,>=3.5->ydata_profiling) (24.1)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\yesmi\anaconda3\lib\site-packages (from matplotlib<=3.10,>=3.5->ydata_profiling) (3.1.2)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\yesmi\anaconda3\lib\site-packages (from matplotlib<=3.10,>=3.5->ydata_profiling) (2.9.0.post0)
Requirement already satisfied: llvmlite<0.44,>=0.43.0dev0 in c:\users\yesmi\anaconda3\lib\site-packages (from numba<=0.61,>=0.56.0->ydata_profiling) (0.43.0)
Requirement already satisfied: pytz>=2020.1 in c:\users\yesmi\anaconda3\lib\site-packages (from pandas!=1.4.0,<3.0,>1.1->ydata_profiling) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\yesmi\anaconda3\lib\site-packages (from pandas!=1.4.0,<3.0,>1.1->ydata_profiling) (2023.3)
Requirement already satisfied: joblib>=0.14.1 in c:\users\yesmi\anaconda3\lib\site-packages (from phik<0.13,>=0.11.1->ydata_profiling) (1.4.2)
Requirement already satisfied: annotated-types>=0.4.0 in c:\users\yesmi\anaconda3\lib\site-packages (from pydantic>=2->ydata_profiling) (0.6.0)
Requirement already satisfied: pydantic-core==2.20.1 in c:\users\yesmi\anaconda3\lib\site-packages (from pydantic>=2->ydata_profiling) (2.20.1)
Requirement already satisfied: typing-extensions>=4.6.1 in c:\users\yesmi\anaconda3\lib\site-packages (from pydantic>=2->ydata_profiling) (4.11.0)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\yesmi\anaconda3\lib\site-packages (from requests<3,>=2.24.0->ydata_profiling) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in c:\users\yesmi\anaconda3\lib\site-packages (from requests<3,>=2.24.0->ydata_profiling) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\yesmi\anaconda3\lib\site-packages (from requests<3,>=2.24.0->ydata_profiling) (2.2.3)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\yesmi\anaconda3\lib\site-packages (from requests<3,>=2.24.0->ydata_profiling) (2024.8.30)
Requirement already satisfied: patsy>=0.5.6 in c:\users\yesmi\anaconda3\lib\site-packages (from statsmodels<1,>=0.13.2->ydata_profiling) (0.5.6)
Requirement already satisfied: colorama in c:\users\yesmi\anaconda3\lib\site-packages (from tqdm<5,>=4.48.2->ydata_profiling) (0.4.6)
Requirement already satisfied: attrs>=19.3.0 in c:\users\yesmi\anaconda3\lib\site-packages (from visions<0.8.2,>=0.7.5->visions[type_image_path]<0.8.2,>=0.7.5->ydata_profiling) (23.1.0)
Requirement already satisfied: networkx>=2.4 in c:\users\yesmi\anaconda3\lib\site-packages (from visions<0.8.2,>=0.7.5->visions[type_image_path]<0.8.2,>=0.7.5->ydata_profiling) (3.3)
Collecting puremagic (from visions<0.8.2,>=0.7.5->visions[type_image_path]<0.8.2,>=0.7.5->ydata_profiling)
  Downloading puremagic-1.29-py3-none-any.whl.metadata (5.8 kB)
Requirement already satisfied: six in c:\users\yesmi\anaconda3\lib\site-packages (from patsy>=0.5.6->statsmodels<1,>=0.13.2->ydata_profiling) (1.16.0)
Downloading ydata_profiling-4.16.1-py2.py3-none-any.whl (400 kB)
Downloading ImageHash-4.3.1-py2.py3-none-any.whl (296 kB)
Downloading dacite-1.9.2-py3-none-any.whl (16 kB)
Downloading multimethod-1.12-py3-none-any.whl (10 kB)
Downloading phik-0.12.4-cp312-cp312-win_amd64.whl (666 kB)
   ---------------------------------------- 0.0/666.4 kB ? eta -:--:--
   --------------- ------------------------ 262.1/666.4 kB ? eta -:--:--
   --------------- ------------------------ 262.1/666.4 kB ? eta -:--:--
   --------------- ------------------------ 262.1/666.4 kB ? eta -:--:--
   --------------- ------------------------ 262.1/666.4 kB ? eta -:--:--
   --------------- ------------------------ 262.1/666.4 kB ? eta -:--:--
   --------------- ------------------------ 262.1/666.4 kB ? eta -:--:--
   -------------------------------------- 666.4/666.4 kB 319.3 kB/s eta 0:00:00
Downloading typeguard-4.4.2-py3-none-any.whl (35 kB)
Downloading visions-0.8.1-py3-none-any.whl (105 kB)
Downloading wordcloud-1.9.4-cp312-cp312-win_amd64.whl (301 kB)
Downloading puremagic-1.29-py3-none-any.whl (43 kB)
Building wheels for collected packages: htmlmin
  Building wheel for htmlmin (setup.py): started
  Building wheel for htmlmin (setup.py): finished with status 'done'
  Created wheel for htmlmin: filename=htmlmin-0.1.12-py3-none-any.whl size=27091 sha256=90da094ffcf5b595024f28dee417543fde8345a795a317087b9d6cd590019724
  Stored in directory: c:\users\yesmi\appdata\local\pip\cache\wheels\5f\d4\d7\4189b07b5902ee9f3ce0dbb14909fbe8037c39d6c63ffd49c9
Successfully built htmlmin
Installing collected packages: puremagic, htmlmin, typeguard, multimethod, dacite, imagehash, wordcloud, visions, phik, ydata_profiling
Successfully installed dacite-1.9.2 htmlmin-0.1.12 imagehash-4.3.1 multimethod-1.12 phik-0.12.4 puremagic-1.29 typeguard-4.4.2 visions-0.8.1 wordcloud-1.9.4 ydata_profiling-4.16.1
Note: you may need to restart the kernel to use updated packages.

In [6]:
pip list

Package                           Version
--------------------------------- ------------------
aext-assistant                    4.0.15
aext-assistant-server             4.0.15
aext-core                         4.0.15
aext-core-server                  4.0.15
aext-panels                       4.0.15
aext-panels-server                4.0.15
aext-share-notebook               4.0.15
aext-share-notebook-server        4.0.15
aext-shared                       4.0.15
aiobotocore                       2.12.3
aiohappyeyeballs                  2.4.0
aiohttp                           3.10.5
aioitertools                      0.7.1
aiosignal                         1.2.0
alabaster                         0.7.16
altair                            5.0.1
anaconda-anon-usage               0.4.4
anaconda-catalogs                 0.2.0
anaconda-client                   1.12.3
anaconda-cloud-auth               0.5.1
anaconda-navigator                2.6.3
anaconda-project                  0.11.1
annotated-types                   0.6.0
anyio                             4.2.0
appdirs                           1.4.4
archspec                          0.2.3
argon2-cffi                       21.3.0
argon2-cffi-bindings              21.2.0
arrow                             1.2.3
astroid                           2.14.2
astropy                           6.1.3
astropy-iers-data                 0.2024.9.2.0.33.23
asttokens                         2.0.5
async-lru                         2.0.4
atomicwrites                      1.4.0
attrs                             23.1.0
Automat                           20.2.0
autopep8                          2.0.4
Babel                             2.11.0
bcrypt                            3.2.0
beautifulsoup4                    4.12.3
binaryornot                       0.4.4
black                             24.8.0
bleach                            4.1.0
blinker                           1.6.2
bokeh                             3.6.0
boltons                           23.0.0
botocore                          1.34.69
Bottleneck                        1.3.7
Brotli                            1.0.9
cachetools                        5.3.3
certifi                           2024.8.30
cffi                              1.17.1
chardet                           4.0.0
charset-normalizer                3.3.2
click                             8.1.7
cloudpickle                       3.0.0
colorama                          0.4.6
colorcet                          3.1.0
comm                              0.2.1
conda                             24.11.0
conda-build                       24.9.0
conda-content-trust               0.2.0
conda_index                       0.5.0
conda-libmamba-solver             24.9.0
conda-pack                        0.7.1
conda-package-handling            2.3.0
conda_package_streaming           0.10.0
conda-repo-cli                    1.0.114
conda-token                       0.5.0+1.g2209e04
constantly                        23.10.4
contourpy                         1.2.0
cookiecutter                      2.6.0
cryptography                      43.0.0
cssselect                         1.2.0
cycler                            0.11.0
cytoolz                           0.12.2
dacite                            1.9.2
dask                              2024.8.2
dask-expr                         1.1.13
datashader                        0.16.3
debugpy                           1.6.7
decorator                         5.1.1
defusedxml                        0.7.1
diff-match-patch                  20200713
dill                              0.3.8
distributed                       2024.8.2
distro                            1.9.0
docstring-to-markdown             0.11
docutils                          0.18.1
et-xmlfile                        1.1.0
executing                         0.8.3
fastjsonschema                    2.16.2
filelock                          3.13.1
flake8                            7.0.0
Flask                             3.0.3
fonttools                         4.51.0
frozendict                        2.4.2
frozenlist                        1.4.0
fsspec                            2024.6.1
gensim                            4.3.3
gitdb                             4.0.7
GitPython                         3.1.43
greenlet                          3.0.1
h11                               0.14.0
h5py                              3.11.0
HeapDict                          1.0.1
holoviews                         1.19.1
htmlmin                           0.1.12
httpcore                          1.0.2
httpx                             0.27.0
hvplot                            0.11.0
hyperlink                         21.0.0
idna                              3.7
imagecodecs                       2023.1.23
ImageHash                         4.3.1
imageio                           2.33.1
imagesize                         1.4.1
imbalanced-learn                  0.12.3
importlib-metadata                7.0.1
incremental                       22.10.0
inflection                        0.5.1
iniconfig                         1.1.1
intake                            2.0.7
intervaltree                      3.1.0
ipykernel                         6.28.0
ipython                           8.27.0
ipython-genutils                  0.2.0
ipywidgets                        7.8.1
isort                             5.13.2
itemadapter                       0.3.0
itemloaders                       1.1.0
itsdangerous                      2.2.0
jaraco.classes                    3.2.1
jedi                              0.19.1
jellyfish                         1.0.1
Jinja2                            3.1.4
jmespath                          1.0.1
joblib                            1.4.2
json5                             0.9.6
jsonpatch                         1.33
jsonpointer                       2.1
jsonschema                        4.23.0
jsonschema-specifications         2023.7.1
jupyter                           1.0.0
jupyter_client                    8.6.0
jupyter-console                   6.6.3
jupyter_core                      5.7.2
jupyter-events                    0.10.0
jupyter-lsp                       2.2.0
jupyter_server                    2.14.1
jupyter_server_terminals          0.4.4
jupyterlab                        4.2.5
jupyterlab-pygments               0.1.2
jupyterlab_server                 2.27.3
jupyterlab-widgets                1.0.0
keyring                           24.3.1
kiwisolver                        1.4.4
lazy_loader                       0.4
lazy-object-proxy                 1.10.0
lckr_jupyterlab_variableinspector 3.1.0
libarchive-c                      5.1
libmambapy                        1.5.8
linkify-it-py                     2.0.0
llvmlite                          0.43.0
lmdb                              1.4.1
locket                            1.0.0
lxml                              5.2.1
lz4                               4.3.2
Markdown                          3.4.1
markdown-it-py                    2.2.0
MarkupSafe                        2.1.3
matplotlib                        3.9.2
matplotlib-inline                 0.1.6
mccabe                            0.7.0
mdit-py-plugins                   0.3.0
mdurl                             0.1.0
menuinst                          2.1.2
mistune                           2.0.4
mkl_fft                           1.3.10
mkl_random                        1.2.7
mkl-service                       2.4.0
more-itertools                    10.3.0
mpmath                            1.3.0
msgpack                           1.0.3
multidict                         6.0.4
multimethod                       1.12
multipledispatch                  0.6.0
mypy                              1.11.2
mypy-extensions                   1.0.0
navigator-updater                 0.5.1
nbclient                          0.8.0
nbconvert                         7.16.4
nbformat                          5.10.4
nest-asyncio                      1.6.0
networkx                          3.3
nltk                              3.9.1
notebook                          7.2.2
notebook_shim                     0.2.3
numba                             0.60.0
numexpr                           2.8.7
numpy                             1.26.4
numpydoc                          1.7.0
openpyxl                          3.1.5
overrides                         7.4.0
packaging                         24.1
pandas                            2.2.2
pandocfilters                     1.5.0
panel                             1.5.2
param                             2.1.1
paramiko                          2.8.1
parsel                            1.8.1
parso                             0.8.3
partd                             1.4.1
pathspec                          0.10.3
patsy                             0.5.6
pexpect                           4.8.0
phik                              0.12.4
pickleshare                       0.7.5
pillow                            10.4.0
pip                               24.2
pkce                              1.0.3
pkginfo                           1.10.0
platformdirs                      3.10.0
plotly                            5.24.1
pluggy                            1.0.0
ply                               3.11
prometheus-client                 0.14.1
prompt-toolkit                    3.0.43
Protego                           0.1.16
protobuf                          4.25.3
psutil                            5.9.0
ptyprocess                        0.7.0
pure-eval                         0.2.2
puremagic                         1.29
py-cpuinfo                        9.0.0
pyarrow                           16.1.0
pyasn1                            0.4.8
pyasn1-modules                    0.2.8
pycodestyle                       2.11.1
pycosat                           0.6.6
pycparser                         2.21
pyct                              0.5.0
pycurl                            7.45.3
pydantic                          2.8.2
pydantic_core                     2.20.1
pydeck                            0.8.0
PyDispatcher                      2.0.5
pydocstyle                        6.3.0
pyerfa                            2.0.1.4
pyflakes                          3.2.0
Pygments                          2.15.1
PyJWT                             2.8.0
pylint                            2.16.2
pylint-venv                       3.0.3
pyls-spyder                       0.4.0
PyNaCl                            1.5.0
pyodbc                            5.1.0
pyOpenSSL                         24.2.1
pyparsing                         3.1.2
PyQt5                             5.15.10
PyQt5-sip                         12.13.0
PyQtWebEngine                     5.15.6
PySocks                           1.7.1
pytest                            7.4.4
python-dateutil                   2.9.0.post0
python-dotenv                     0.21.0
python-json-logger                2.0.7
python-lsp-black                  2.0.0
python-lsp-jsonrpc                1.1.2
python-lsp-server                 1.10.0
python-slugify                    5.0.2
pytoolconfig                      1.2.6
pytz                              2024.1
pyviz_comms                       3.0.2
PyWavelets                        1.7.0
pywin32                           305.1
pywin32-ctypes                    0.2.2
pywinpty                          2.0.10
PyYAML                            6.0.1
pyzmq                             25.1.2
QDarkStyle                        3.2.3
qstylizer                         0.2.2
QtAwesome                         1.3.1
qtconsole                         5.5.1
QtPy                              2.4.1
queuelib                          1.6.2
referencing                       0.30.2
regex                             2024.9.11
requests                          2.32.3
requests-file                     1.5.1
requests-toolbelt                 1.0.0
rfc3339-validator                 0.1.4
rfc3986-validator                 0.1.1
rich                              13.7.1
rope                              1.12.0
rpds-py                           0.10.6
Rtree                             1.0.1
ruamel.yaml                       0.18.6
ruamel.yaml.clib                  0.2.8
ruamel-yaml-conda                 0.17.21
s3fs                              2024.6.1
scikit-image                      0.24.0
scikit-learn                      1.5.1
scipy                             1.13.1
Scrapy                            2.11.1
seaborn                           0.13.2
semver                            3.0.2
Send2Trash                        1.8.2
service-identity                  18.1.0
setuptools                        75.1.0
sip                               6.7.12
six                               1.16.0
smart-open                        5.2.1
smmap                             4.0.0
sniffio                           1.3.0
snowballstemmer                   2.2.0
sortedcontainers                  2.4.0
soupsieve                         2.5
Sphinx                            7.3.7
sphinxcontrib-applehelp           1.0.2
sphinxcontrib-devhelp             1.0.2
sphinxcontrib-htmlhelp            2.0.0
sphinxcontrib-jsmath              1.0.1
sphinxcontrib-qthelp              1.0.3
sphinxcontrib-serializinghtml     1.1.10
spyder                            5.5.1
spyder-kernels                    2.5.0
SQLAlchemy                        2.0.34
stack-data                        0.2.0
statsmodels                       0.14.2
streamlit                         1.37.1
sympy                             1.13.2
tables                            3.10.1
tabulate                          0.9.0
tblib                             1.7.0
tenacity                          8.2.3
terminado                         0.17.1
text-unidecode                    1.3
textdistance                      4.2.1
threadpoolctl                     3.5.0
three-merge                       0.1.1
tifffile                          2023.4.12
tinycss2                          1.2.1
tldextract                        5.1.2
toml                              0.10.2
tomli                             2.0.1
tomlkit                           0.11.1
toolz                             0.12.0
tornado                           6.4.1
tqdm                              4.66.5
traitlets                         5.14.3
truststore                        0.8.0
Twisted                           23.10.0
twisted-iocpsupport               1.0.2
typeguard                         4.4.2
typing_extensions                 4.11.0
tzdata                            2023.3
uc-micro-py                       1.0.1
ujson                             5.10.0
unicodedata2                      15.1.0
Unidecode                         1.3.8
urllib3                           2.2.3
visions                           0.8.1
w3lib                             2.1.2
watchdog                          4.0.1
wcwidth                           0.2.5
webencodings                      0.5.1
websocket-client                  1.8.0
Werkzeug                          3.0.3
whatthepatch                      1.0.2
wheel                             0.44.0
widgetsnbextension                3.6.6
win-inet-pton                     1.1.0
wordcloud                         1.9.4
wrapt                             1.14.1
xarray                            2023.6.0
xlwings                           0.32.1
xyzservices                       2022.9.0
yapf                              0.40.2
yarl                              1.11.0
ydata-profiling                   4.16.1
zict                              3.0.0
zipp                              3.17.0
zope.interface                    5.4.0
zstandard                         0.23.0
Note: you may need to restart the kernel to use updated packages.

In [9]:
import pandas as pd

Importer une donnée de notre ordi - on transforme notre fichier csv en notre data frame: 
-Mettre r avant le path pour qu'il puisse être pris en compte
-changer le read_excel en read_csv en dépend du type de fichier qu'on a

In [21]:
df = pd.read_excel(r"C:\\Users\\yesmi\\OneDrive\\Bureau\\M2 PGE DSBI\\python\\liquor_store_sales (1).xlsx")

To read our variable(data frame) we can just run 'df' or 'print(df)'

In [24]:
df

,Year,Month,Supplier,ItemCode,Description,ItemType,RetailSales,RetailTransfers,WarehouseSales
0,2017,4,ROYAL WINE CORP,100200,GAMLA CAB - 750ML,WINE,0.00,1.0,0.0
1,2017,4,SANTA MARGHERITA USA INC,100749,SANTA MARGHERITA P/GRIG ALTO - 375ML,WINE,0.00,1.0,0.0
2,2017,4,JIM BEAM BRANDS CO,10103,KNOB CREEK BOURBON 9YR - 100P - 375ML,LIQUOR,0.00,8.0,0.0
3,2017,4,HEAVEN HILL DISTILLERIES INC,10120,J W DANT BOURBON 100P - 1.75L,LIQUOR,0.00,2.0,0.0
4,2017,4,ROYAL WINE CORP,101664,RAMON CORDOVA RIOJA - 750ML,WINE,0.00,4.0,0.0
...,...,...,...,...,...,...,...,...,...
128350,2018,2,ANHEUSER BUSCH INC,9997,HOEGAARDEN 4/6NR - 12OZ,BEER,66.46,59.0,212.0
128351,2018,2,COASTAL BREWING COMPANY LLC,99970,DOMINION OAK BARREL STOUT 4/6 NR - 12OZ,BEER,9.08,7.0,35.0
128352,2018,2,BOSTON BEER CORPORATION,99988,SAM ADAMS COLD SNAP 1/6 KG,KEGS,0.00,0.0,32.0
128353,2018,2,NaN,BC,BEER CREDIT,REF,0.00,0.0,-35.0
128354,2018,2,NaN,WC,WINE CREDIT,REF,0.00,0.0,-81.0

Apply on the data frame

In [27]:
df.head()

,Year,Month,Supplier,ItemCode,Description,ItemType,RetailSales,RetailTransfers,WarehouseSales
0,2017,4,ROYAL WINE CORP,100200,GAMLA CAB - 750ML,WINE,0.0,1.0,0.0
1,2017,4,SANTA MARGHERITA USA INC,100749,SANTA MARGHERITA P/GRIG ALTO - 375ML,WINE,0.0,1.0,0.0
2,2017,4,JIM BEAM BRANDS CO,10103,KNOB CREEK BOURBON 9YR - 100P - 375ML,LIQUOR,0.0,8.0,0.0
3,2017,4,HEAVEN HILL DISTILLERIES INC,10120,J W DANT BOURBON 100P - 1.75L,LIQUOR,0.0,2.0,0.0
4,2017,4,ROYAL WINE CORP,101664,RAMON CORDOVA RIOJA - 750ML,WINE,0.0,4.0,0.0

In [29]:
df.head(3)

,Year,Month,Supplier,ItemCode,Description,ItemType,RetailSales,RetailTransfers,WarehouseSales
0,2017,4,ROYAL WINE CORP,100200,GAMLA CAB - 750ML,WINE,0.0,1.0,0.0
1,2017,4,SANTA MARGHERITA USA INC,100749,SANTA MARGHERITA P/GRIG ALTO - 375ML,WINE,0.0,1.0,0.0
2,2017,4,JIM BEAM BRANDS CO,10103,KNOB CREEK BOURBON 9YR - 100P - 375ML,LIQUOR,0.0,8.0,0.0

In [31]:
df.describe()

,Year,Month,RetailSales,RetailTransfers,WarehouseSales
count,128355.000000,128355.000000,128355.000000,128355.000000,128355.000000
mean,2017.206030,7.079303,6.563037,7.188161,22.624213
std,0.404454,3.645826,28.924944,30.640156,239.693277
min,2017.000000,1.000000,-6.490000,-27.660000,-4996.000000
25%,2017.000000,5.000000,0.000000,0.000000,0.000000
50%,2017.000000,8.000000,0.330000,0.000000,1.000000
75%,2017.000000,10.000000,3.250000,4.000000,4.000000
max,2018.000000,12.000000,1616.600000,1587.990000,16271.750000

quand on a des info numeriques et non numériques: la correlation ne fonctionne pas il faut que tout soit numérique
df.corr() - pour que ça fonctionne on ne doit séléctionner que les informations numériques

df pour accéder à toute la data frame
pour accéder à la colonne  df["Year"] OU BIEN df.Year

In [36]:
df.Year

0         2017
1         2017
2         2017
3         2017
4         2017
          ...
128350    2018
128351    2018
128352    2018
128353    2018
128354    2018
Name: Year, Length: 128355, dtype: int64